;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        backward-sexp
        backward-up-list
        c-electric-delete-forward
        delete-horizontal-space
        down-list
        duplicate-line-below
        duplicate-line-or-region-below
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        skk-insert
        sp-remove-active-pair-overlay
        sp-rewrap-sexp
        sp-unwrap-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        compilation-next-error
        counsel-M-x
        counsel-switch-buffer
        handle-switch-frame
        ignore
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        lsp-signature-stop
        lsp-ui-doc--handle-mouse-movement
        mc/mark-next-lines
        mc/mark-previous-lines
        org-cycle
        vterm-or-suspend
        ))
