;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-sub-or-superscript
        backward-sexp
        backward-up-list
        delete-horizontal-space
        down-list
        forward-sexp
        kill-region
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        org-delete-char
        org-self-insert-command
        sp-unwrap-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        handle-switch-frame
        ignore
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        lsp-signature-stop
        lsp-ui-doc--handle-mouse-movement
        mc/mark-next-lines
        mc/mark-previous-lines
        vterm-or-suspend
        ))
